// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package ai.h2o.deepwater;

public interface NetworkResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deepwater.NetworkResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .tensorflow.MetaGraphDef network = 1;</code>
   */
  boolean hasNetwork();
  /**
   * <code>optional .tensorflow.MetaGraphDef network = 1;</code>
   */
  org.tensorflow.framework.MetaGraphDef getNetwork();
  /**
   * <code>optional .tensorflow.MetaGraphDef network = 1;</code>
   */
  org.tensorflow.framework.MetaGraphDefOrBuilder getNetworkOrBuilder();

  /**
   * <code>optional .deepwater.Status status = 2;</code>
   */
  boolean hasStatus();
  /**
   * <code>optional .deepwater.Status status = 2;</code>
   */
  ai.h2o.deepwater.Status getStatus();
  /**
   * <code>optional .deepwater.Status status = 2;</code>
   */
  ai.h2o.deepwater.StatusOrBuilder getStatusOrBuilder();
}
