// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package ai.h2o.deepwater;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deepwater.Status)
    com.google.protobuf.MessageOrBuilder {
}
