// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_service.proto

package ai.h2o.deepwater.backends.grpc;

public interface SetParametersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deepwater.SetParametersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .deepwater.BackendModel model = 1;</code>
   */
  boolean hasModel();
  /**
   * <code>optional .deepwater.BackendModel model = 1;</code>
   */
  ai.h2o.deepwater.backends.grpc.BackendModel getModel();
  /**
   * <code>optional .deepwater.BackendModel model = 1;</code>
   */
  ai.h2o.deepwater.backends.grpc.BackendModelOrBuilder getModelOrBuilder();

  /**
   * <code>map&lt;string, .deepwater.ParamValue&gt; params = 2;</code>
   */
  int getParamsCount();
  /**
   * <code>map&lt;string, .deepwater.ParamValue&gt; params = 2;</code>
   */
  boolean containsParams(
      java.lang.String key);
  /**
   * Use {@link #getParamsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, ai.h2o.deepwater.backends.grpc.ParamValue>
  getParams();
  /**
   * <code>map&lt;string, .deepwater.ParamValue&gt; params = 2;</code>
   */
  java.util.Map<java.lang.String, ai.h2o.deepwater.backends.grpc.ParamValue>
  getParamsMap();
  /**
   * <code>map&lt;string, .deepwater.ParamValue&gt; params = 2;</code>
   */

  ai.h2o.deepwater.backends.grpc.ParamValue getParamsOrDefault(
      java.lang.String key,
      ai.h2o.deepwater.backends.grpc.ParamValue defaultValue);
  /**
   * <code>map&lt;string, .deepwater.ParamValue&gt; params = 2;</code>
   */

  ai.h2o.deepwater.backends.grpc.ParamValue getParamsOrThrow(
      java.lang.String key);
}
