// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_service.proto

package ai.h2o.deepwater.backends.grpc;

public interface TrainRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deepwater.TrainRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .deepwater.BackendModel model = 1;</code>
   */
  boolean hasModel();
  /**
   * <code>optional .deepwater.BackendModel model = 1;</code>
   */
  ai.h2o.deepwater.backends.grpc.BackendModel getModel();
  /**
   * <code>optional .deepwater.BackendModel model = 1;</code>
   */
  ai.h2o.deepwater.backends.grpc.BackendModelOrBuilder getModelOrBuilder();

  /**
   * <code>repeated .deepwater.Tensor feeds = 2;</code>
   */
  java.util.List<ai.h2o.deepwater.backends.grpc.Tensor> 
      getFeedsList();
  /**
   * <code>repeated .deepwater.Tensor feeds = 2;</code>
   */
  ai.h2o.deepwater.backends.grpc.Tensor getFeeds(int index);
  /**
   * <code>repeated .deepwater.Tensor feeds = 2;</code>
   */
  int getFeedsCount();
  /**
   * <code>repeated .deepwater.Tensor feeds = 2;</code>
   */
  java.util.List<? extends ai.h2o.deepwater.backends.grpc.TensorOrBuilder> 
      getFeedsOrBuilderList();
  /**
   * <code>repeated .deepwater.Tensor feeds = 2;</code>
   */
  ai.h2o.deepwater.backends.grpc.TensorOrBuilder getFeedsOrBuilder(
      int index);

  /**
   * <code>repeated .deepwater.Tensor fetches = 3;</code>
   */
  java.util.List<ai.h2o.deepwater.backends.grpc.Tensor> 
      getFetchesList();
  /**
   * <code>repeated .deepwater.Tensor fetches = 3;</code>
   */
  ai.h2o.deepwater.backends.grpc.Tensor getFetches(int index);
  /**
   * <code>repeated .deepwater.Tensor fetches = 3;</code>
   */
  int getFetchesCount();
  /**
   * <code>repeated .deepwater.Tensor fetches = 3;</code>
   */
  java.util.List<? extends ai.h2o.deepwater.backends.grpc.TensorOrBuilder> 
      getFetchesOrBuilderList();
  /**
   * <code>repeated .deepwater.Tensor fetches = 3;</code>
   */
  ai.h2o.deepwater.backends.grpc.TensorOrBuilder getFetchesOrBuilder(
      int index);
}
