// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_service.proto

package ai.h2o.deepwater.backends.grpc;

public final class DeepWaterGRPCService {
  private DeepWaterGRPCService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_Session_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_Session_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_BackendModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_BackendModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_DeleteModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_DeleteModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_CreateModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_CreateModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_CreateModelRequest_ParamsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_CreateModelRequest_ParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_CreateModelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_CreateModelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_Status_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_LoadModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_LoadModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_SaveModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_SaveModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_LoadWeightsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_LoadWeightsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_SaveWeightsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_SaveWeightsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_SetParametersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_SetParametersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_SetParametersRequest_ParamsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_SetParametersRequest_ParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_TrainRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_TrainRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_TrainResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_TrainResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_PredictRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_PredictRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_PredictResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_PredictResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_Shape_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_Shape_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_Shape_Dim_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_Shape_Dim_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_Tensor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_Tensor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_ParamValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_ParamValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deepwater_ParamValue_ListValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deepwater_ParamValue_ListValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022grpc_service.proto\022\tdeepwater\"\025\n\007Sessi" +
      "on\022\n\n\002id\030\001 \001(\t\"\035\n\014BackendModel\022\r\n\005state\030" +
      "\001 \001(\014\"<\n\022DeleteModelRequest\022&\n\005model\030\001 \001" +
      "(\0132\027.deepwater.BackendModel\"\250\001\n\022CreateMo" +
      "delRequest\022\021\n\tmodelName\030\001 \001(\t\0229\n\006params\030" +
      "\002 \003(\0132).deepwater.CreateModelRequest.Par" +
      "amsEntry\032D\n\013ParamsEntry\022\013\n\003key\030\001 \001(\t\022$\n\005" +
      "value\030\002 \001(\0132\025.deepwater.ParamValue:\0028\001\"I" +
      "\n\023CreateModelResponse\022\017\n\007network\030\001 \001(\014\022!" +
      "\n\006status\030\002 \001(\0132\021.deepwater.Status\"%\n\006Sta",
      "tus\022\n\n\002ok\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"m\n\020Load" +
      "ModelRequest\022#\n\007session\030\001 \001(\0132\022.deepwate" +
      "r.Session\022&\n\005model\030\002 \001(\0132\027.deepwater.Bac" +
      "kendModel\022\014\n\004path\030\003 \001(\014\"m\n\020SaveModelRequ" +
      "est\022#\n\007session\030\001 \001(\0132\022.deepwater.Session" +
      "\022&\n\005model\030\002 \001(\0132\027.deepwater.BackendModel" +
      "\022\014\n\004path\030\003 \001(\014\"o\n\022LoadWeightsRequest\022#\n\007" +
      "session\030\001 \001(\0132\022.deepwater.Session\022&\n\005mod" +
      "el\030\002 \001(\0132\027.deepwater.BackendModel\022\014\n\004pat" +
      "h\030\003 \001(\014\"J\n\022SaveWeightsRequest\022&\n\005model\030\001",
      " \001(\0132\027.deepwater.BackendModel\022\014\n\004path\030\002 " +
      "\001(\014\"\301\001\n\024SetParametersRequest\022&\n\005model\030\001 " +
      "\001(\0132\027.deepwater.BackendModel\022;\n\006params\030\002" +
      " \003(\0132+.deepwater.SetParametersRequest.Pa" +
      "ramsEntry\032D\n\013ParamsEntry\022\013\n\003key\030\001 \001(\t\022$\n" +
      "\005value\030\002 \001(\0132\025.deepwater.ParamValue:\0028\001\"" +
      "|\n\014TrainRequest\022&\n\005model\030\001 \001(\0132\027.deepwat" +
      "er.BackendModel\022 \n\005feeds\030\002 \003(\0132\021.deepwat" +
      "er.Tensor\022\"\n\007fetches\030\003 \003(\0132\021.deepwater.T" +
      "ensor\"[\n\rTrainResponse\022&\n\005model\030\001 \001(\0132\027.",
      "deepwater.BackendModel\022\"\n\007fetches\030\003 \003(\0132" +
      "\021.deepwater.Tensor\"~\n\016PredictRequest\022&\n\005" +
      "model\030\001 \001(\0132\027.deepwater.BackendModel\022 \n\005" +
      "feeds\030\002 \003(\0132\021.deepwater.Tensor\022\"\n\007fetche" +
      "s\030\003 \003(\0132\021.deepwater.Tensor\"X\n\017PredictRes" +
      "ponse\022\"\n\007fetches\030\001 \003(\0132\021.deepwater.Tenso" +
      "r\022!\n\006status\030\002 \001(\0132\021.deepwater.Status\"?\n\005" +
      "Shape\022!\n\003dim\030\002 \003(\0132\024.deepwater.Shape.Dim" +
      "\032\023\n\003Dim\022\014\n\004size\030\001 \001(\003\"\355\001\n\006Tensor\022\037\n\005shap" +
      "e\030\001 \001(\0132\020.deepwater.Shape\022!\n\004type\030\002 \001(\0162",
      "\023.deepwater.DataType\022\014\n\004name\030\003 \001(\t\022\024\n\014st" +
      "ring_value\030\004 \003(\014\022\027\n\013int32_value\030\005 \003(\005B\002\020" +
      "\001\022\027\n\013int64_value\030\006 \003(\003B\002\020\001\022\027\n\013float_valu" +
      "e\030\007 \003(\002B\002\020\001\022\030\n\014double_value\030\010 \003(\001B\002\020\001\022\026\n" +
      "\nbool_value\030\t \003(\010B\002\020\001\"\333\001\n\nParamValue\022\013\n\001" +
      "s\030\002 \001(\014H\000\022\013\n\001i\030\003 \001(\003H\000\022\013\n\001f\030\004 \001(\002H\000\022\013\n\001d" +
      "\030\005 \001(\001H\000\022\013\n\001b\030\006 \001(\010H\000\022/\n\004list\030\001 \001(\0132\037.de" +
      "epwater.ParamValue.ListValueH\000\032R\n\tListVa" +
      "lue\022\t\n\001s\030\002 \003(\014\022\r\n\001i\030\003 \003(\003B\002\020\001\022\r\n\001c\030\004 \003(\002" +
      "B\002\020\001\022\r\n\001f\030\005 \003(\001B\002\020\001\022\r\n\001b\030\006 \003(\010B\002\020\001B\007\n\005va",
      "lue*r\n\010DataType\022\016\n\nDT_INVALID\020\000\022\016\n\nDT_FL" +
      "OAT32\020\001\022\016\n\nDT_FLOAT64\020\002\022\014\n\010DT_INT32\020\003\022\014\n" +
      "\010DT_INT64\020\004\022\013\n\007DT_BOOL\020\005\022\r\n\tDT_STRING\020\0062" +
      "T\n\027DeepWaterPredictBackend\0229\n\007Predict\022\031." +
      "deepwater.PredictRequest\032\021.deepwater.Sta" +
      "tus\"\0002\347\004\n\025DeepWaterTrainBackend\022N\n\013Creat" +
      "eModel\022\035.deepwater.CreateModelRequest\032\036." +
      "deepwater.CreateModelResponse\"\000\022A\n\013Delet" +
      "eModel\022\035.deepwater.DeleteModelRequest\032\021." +
      "deepwater.Status\"\000\022=\n\tLoadModel\022\033.deepwa",
      "ter.LoadModelRequest\032\021.deepwater.Status\"" +
      "\000\022=\n\tSaveModel\022\033.deepwater.SaveModelRequ" +
      "est\032\021.deepwater.Status\"\000\022A\n\013LoadWeights\022" +
      "\035.deepwater.LoadWeightsRequest\032\021.deepwat" +
      "er.Status\"\000\022A\n\013SaveWeights\022\035.deepwater.S" +
      "aveWeightsRequest\032\021.deepwater.Status\"\000\022E" +
      "\n\rSetParameters\022\037.deepwater.SetParameter" +
      "sRequest\032\021.deepwater.Status\"\000\0225\n\005Train\022\027" +
      ".deepwater.TrainRequest\032\021.deepwater.Stat" +
      "us\"\000\0229\n\007Predict\022\031.deepwater.PredictReque",
      "st\032\021.deepwater.Status\"\000B8\n\036ai.h2o.deepwa" +
      "ter.backends.grpcB\024DeepWaterGRPCServiceP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_deepwater_Session_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_deepwater_Session_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_Session_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_deepwater_BackendModel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_deepwater_BackendModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_BackendModel_descriptor,
        new java.lang.String[] { "State", });
    internal_static_deepwater_DeleteModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_deepwater_DeleteModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_DeleteModelRequest_descriptor,
        new java.lang.String[] { "Model", });
    internal_static_deepwater_CreateModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_deepwater_CreateModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_CreateModelRequest_descriptor,
        new java.lang.String[] { "ModelName", "Params", });
    internal_static_deepwater_CreateModelRequest_ParamsEntry_descriptor =
      internal_static_deepwater_CreateModelRequest_descriptor.getNestedTypes().get(0);
    internal_static_deepwater_CreateModelRequest_ParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_CreateModelRequest_ParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_deepwater_CreateModelResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_deepwater_CreateModelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_CreateModelResponse_descriptor,
        new java.lang.String[] { "Network", "Status", });
    internal_static_deepwater_Status_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_deepwater_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_Status_descriptor,
        new java.lang.String[] { "Ok", "Message", });
    internal_static_deepwater_LoadModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_deepwater_LoadModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_LoadModelRequest_descriptor,
        new java.lang.String[] { "Session", "Model", "Path", });
    internal_static_deepwater_SaveModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_deepwater_SaveModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_SaveModelRequest_descriptor,
        new java.lang.String[] { "Session", "Model", "Path", });
    internal_static_deepwater_LoadWeightsRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_deepwater_LoadWeightsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_LoadWeightsRequest_descriptor,
        new java.lang.String[] { "Session", "Model", "Path", });
    internal_static_deepwater_SaveWeightsRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_deepwater_SaveWeightsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_SaveWeightsRequest_descriptor,
        new java.lang.String[] { "Model", "Path", });
    internal_static_deepwater_SetParametersRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_deepwater_SetParametersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_SetParametersRequest_descriptor,
        new java.lang.String[] { "Model", "Params", });
    internal_static_deepwater_SetParametersRequest_ParamsEntry_descriptor =
      internal_static_deepwater_SetParametersRequest_descriptor.getNestedTypes().get(0);
    internal_static_deepwater_SetParametersRequest_ParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_SetParametersRequest_ParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_deepwater_TrainRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_deepwater_TrainRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_TrainRequest_descriptor,
        new java.lang.String[] { "Model", "Feeds", "Fetches", });
    internal_static_deepwater_TrainResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_deepwater_TrainResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_TrainResponse_descriptor,
        new java.lang.String[] { "Model", "Fetches", });
    internal_static_deepwater_PredictRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_deepwater_PredictRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_PredictRequest_descriptor,
        new java.lang.String[] { "Model", "Feeds", "Fetches", });
    internal_static_deepwater_PredictResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_deepwater_PredictResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_PredictResponse_descriptor,
        new java.lang.String[] { "Fetches", "Status", });
    internal_static_deepwater_Shape_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_deepwater_Shape_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_Shape_descriptor,
        new java.lang.String[] { "Dim", });
    internal_static_deepwater_Shape_Dim_descriptor =
      internal_static_deepwater_Shape_descriptor.getNestedTypes().get(0);
    internal_static_deepwater_Shape_Dim_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_Shape_Dim_descriptor,
        new java.lang.String[] { "Size", });
    internal_static_deepwater_Tensor_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_deepwater_Tensor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_Tensor_descriptor,
        new java.lang.String[] { "Shape", "Type", "Name", "StringValue", "Int32Value", "Int64Value", "FloatValue", "DoubleValue", "BoolValue", });
    internal_static_deepwater_ParamValue_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_deepwater_ParamValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_ParamValue_descriptor,
        new java.lang.String[] { "S", "I", "F", "D", "B", "List", "Value", });
    internal_static_deepwater_ParamValue_ListValue_descriptor =
      internal_static_deepwater_ParamValue_descriptor.getNestedTypes().get(0);
    internal_static_deepwater_ParamValue_ListValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deepwater_ParamValue_ListValue_descriptor,
        new java.lang.String[] { "S", "I", "C", "F", "B", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
