// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_service.proto

package ai.h2o.deepwater.backends.grpc;

public interface LoadModelResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deepwater.LoadModelResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .deepwater.BackendModel model = 1;</code>
   */
  boolean hasModel();
  /**
   * <code>optional .deepwater.BackendModel model = 1;</code>
   */
  ai.h2o.deepwater.backends.grpc.BackendModel getModel();
  /**
   * <code>optional .deepwater.BackendModel model = 1;</code>
   */
  ai.h2o.deepwater.backends.grpc.BackendModelOrBuilder getModelOrBuilder();

  /**
   * <code>optional .deepwater.Status status = 2;</code>
   */
  boolean hasStatus();
  /**
   * <code>optional .deepwater.Status status = 2;</code>
   */
  ai.h2o.deepwater.backends.grpc.Status getStatus();
  /**
   * <code>optional .deepwater.Status status = 2;</code>
   */
  ai.h2o.deepwater.backends.grpc.StatusOrBuilder getStatusOrBuilder();
}
