// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_service.proto

package ai.h2o.deepwater.backends.grpc;

public interface LoadModelVariablesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deepwater.LoadModelVariablesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .deepwater.Status status = 1;</code>
   */
  boolean hasStatus();
  /**
   * <code>optional .deepwater.Status status = 1;</code>
   */
  ai.h2o.deepwater.backends.grpc.Status getStatus();
  /**
   * <code>optional .deepwater.Status status = 1;</code>
   */
  ai.h2o.deepwater.backends.grpc.StatusOrBuilder getStatusOrBuilder();
}
