// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_service.proto

package ai.h2o.deepwater.backends.grpc;

/**
 * Protobuf type {@code deepwater.ParamValue}
 */
public  final class ParamValue extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:deepwater.ParamValue)
    ParamValueOrBuilder {
  // Use ParamValue.newBuilder() to construct.
  private ParamValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ParamValue() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ParamValue(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.Builder subBuilder = null;
            if (valueCase_ == 1) {
              subBuilder = ((ai.h2o.deepwater.backends.grpc.ParamValue.ListValue) value_).toBuilder();
            }
            value_ =
                input.readMessage(ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ai.h2o.deepwater.backends.grpc.ParamValue.ListValue) value_);
              value_ = subBuilder.buildPartial();
            }
            valueCase_ = 1;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            valueCase_ = 2;
            value_ = s;
            break;
          }
          case 24: {
            valueCase_ = 3;
            value_ = input.readInt64();
            break;
          }
          case 37: {
            valueCase_ = 4;
            value_ = input.readFloat();
            break;
          }
          case 41: {
            valueCase_ = 5;
            value_ = input.readDouble();
            break;
          }
          case 48: {
            valueCase_ = 6;
            value_ = input.readBool();
            break;
          }
          case 58: {
            valueCase_ = 7;
            value_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.h2o.deepwater.backends.grpc.DeepWaterGRPCService.internal_static_deepwater_ParamValue_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.h2o.deepwater.backends.grpc.DeepWaterGRPCService.internal_static_deepwater_ParamValue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.h2o.deepwater.backends.grpc.ParamValue.class, ai.h2o.deepwater.backends.grpc.ParamValue.Builder.class);
  }

  public interface ListValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:deepwater.ParamValue.ListValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * "list(string)"
     * </pre>
     *
     * <code>repeated string s = 2;</code>
     */
    java.util.List<java.lang.String>
        getSList();
    /**
     * <pre>
     * "list(string)"
     * </pre>
     *
     * <code>repeated string s = 2;</code>
     */
    int getSCount();
    /**
     * <pre>
     * "list(string)"
     * </pre>
     *
     * <code>repeated string s = 2;</code>
     */
    java.lang.String getS(int index);
    /**
     * <pre>
     * "list(string)"
     * </pre>
     *
     * <code>repeated string s = 2;</code>
     */
    com.google.protobuf.ByteString
        getSBytes(int index);

    /**
     * <pre>
     * "list(int)"
     * </pre>
     *
     * <code>repeated int64 i = 3 [packed = true];</code>
     */
    java.util.List<java.lang.Long> getIList();
    /**
     * <pre>
     * "list(int)"
     * </pre>
     *
     * <code>repeated int64 i = 3 [packed = true];</code>
     */
    int getICount();
    /**
     * <pre>
     * "list(int)"
     * </pre>
     *
     * <code>repeated int64 i = 3 [packed = true];</code>
     */
    long getI(int index);

    /**
     * <pre>
     * "list(float)"
     * </pre>
     *
     * <code>repeated float c = 4 [packed = true];</code>
     */
    java.util.List<java.lang.Float> getCList();
    /**
     * <pre>
     * "list(float)"
     * </pre>
     *
     * <code>repeated float c = 4 [packed = true];</code>
     */
    int getCCount();
    /**
     * <pre>
     * "list(float)"
     * </pre>
     *
     * <code>repeated float c = 4 [packed = true];</code>
     */
    float getC(int index);

    /**
     * <pre>
     * "list(double)"
     * </pre>
     *
     * <code>repeated double f = 5 [packed = true];</code>
     */
    java.util.List<java.lang.Double> getFList();
    /**
     * <pre>
     * "list(double)"
     * </pre>
     *
     * <code>repeated double f = 5 [packed = true];</code>
     */
    int getFCount();
    /**
     * <pre>
     * "list(double)"
     * </pre>
     *
     * <code>repeated double f = 5 [packed = true];</code>
     */
    double getF(int index);

    /**
     * <pre>
     * "list(bool)"
     * </pre>
     *
     * <code>repeated bool b = 6 [packed = true];</code>
     */
    java.util.List<java.lang.Boolean> getBList();
    /**
     * <pre>
     * "list(bool)"
     * </pre>
     *
     * <code>repeated bool b = 6 [packed = true];</code>
     */
    int getBCount();
    /**
     * <pre>
     * "list(bool)"
     * </pre>
     *
     * <code>repeated bool b = 6 [packed = true];</code>
     */
    boolean getB(int index);

    /**
     * <code>repeated bool bb = 7 [packed = true];</code>
     */
    java.util.List<java.lang.Boolean> getBbList();
    /**
     * <code>repeated bool bb = 7 [packed = true];</code>
     */
    int getBbCount();
    /**
     * <code>repeated bool bb = 7 [packed = true];</code>
     */
    boolean getBb(int index);
  }
  /**
   * Protobuf type {@code deepwater.ParamValue.ListValue}
   */
  public  static final class ListValue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:deepwater.ParamValue.ListValue)
      ListValueOrBuilder {
    // Use ListValue.newBuilder() to construct.
    private ListValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListValue() {
      s_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      i_ = java.util.Collections.emptyList();
      c_ = java.util.Collections.emptyList();
      f_ = java.util.Collections.emptyList();
      b_ = java.util.Collections.emptyList();
      bb_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ListValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                s_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              s_.add(s);
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                i_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              i_.add(input.readInt64());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                i_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                i_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 37: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                c_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000004;
              }
              c_.add(input.readFloat());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                c_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                c_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 41: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                f_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000008;
              }
              f_.add(input.readDouble());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                f_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                f_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                b_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000010;
              }
              b_.add(input.readBool());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                b_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                b_.add(input.readBool());
              }
              input.popLimit(limit);
              break;
            }
            case 56: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                bb_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000020;
              }
              bb_.add(input.readBool());
              break;
            }
            case 58: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
                bb_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000020;
              }
              while (input.getBytesUntilLimit() > 0) {
                bb_.add(input.readBool());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          s_ = s_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          i_ = java.util.Collections.unmodifiableList(i_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          c_ = java.util.Collections.unmodifiableList(c_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          f_ = java.util.Collections.unmodifiableList(f_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          b_ = java.util.Collections.unmodifiableList(b_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          bb_ = java.util.Collections.unmodifiableList(bb_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.h2o.deepwater.backends.grpc.DeepWaterGRPCService.internal_static_deepwater_ParamValue_ListValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.h2o.deepwater.backends.grpc.DeepWaterGRPCService.internal_static_deepwater_ParamValue_ListValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.class, ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.Builder.class);
    }

    public static final int S_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList s_;
    /**
     * <pre>
     * "list(string)"
     * </pre>
     *
     * <code>repeated string s = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSList() {
      return s_;
    }
    /**
     * <pre>
     * "list(string)"
     * </pre>
     *
     * <code>repeated string s = 2;</code>
     */
    public int getSCount() {
      return s_.size();
    }
    /**
     * <pre>
     * "list(string)"
     * </pre>
     *
     * <code>repeated string s = 2;</code>
     */
    public java.lang.String getS(int index) {
      return s_.get(index);
    }
    /**
     * <pre>
     * "list(string)"
     * </pre>
     *
     * <code>repeated string s = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSBytes(int index) {
      return s_.getByteString(index);
    }

    public static final int I_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Long> i_;
    /**
     * <pre>
     * "list(int)"
     * </pre>
     *
     * <code>repeated int64 i = 3 [packed = true];</code>
     */
    public java.util.List<java.lang.Long>
        getIList() {
      return i_;
    }
    /**
     * <pre>
     * "list(int)"
     * </pre>
     *
     * <code>repeated int64 i = 3 [packed = true];</code>
     */
    public int getICount() {
      return i_.size();
    }
    /**
     * <pre>
     * "list(int)"
     * </pre>
     *
     * <code>repeated int64 i = 3 [packed = true];</code>
     */
    public long getI(int index) {
      return i_.get(index);
    }
    private int iMemoizedSerializedSize = -1;

    public static final int C_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Float> c_;
    /**
     * <pre>
     * "list(float)"
     * </pre>
     *
     * <code>repeated float c = 4 [packed = true];</code>
     */
    public java.util.List<java.lang.Float>
        getCList() {
      return c_;
    }
    /**
     * <pre>
     * "list(float)"
     * </pre>
     *
     * <code>repeated float c = 4 [packed = true];</code>
     */
    public int getCCount() {
      return c_.size();
    }
    /**
     * <pre>
     * "list(float)"
     * </pre>
     *
     * <code>repeated float c = 4 [packed = true];</code>
     */
    public float getC(int index) {
      return c_.get(index);
    }
    private int cMemoizedSerializedSize = -1;

    public static final int F_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Double> f_;
    /**
     * <pre>
     * "list(double)"
     * </pre>
     *
     * <code>repeated double f = 5 [packed = true];</code>
     */
    public java.util.List<java.lang.Double>
        getFList() {
      return f_;
    }
    /**
     * <pre>
     * "list(double)"
     * </pre>
     *
     * <code>repeated double f = 5 [packed = true];</code>
     */
    public int getFCount() {
      return f_.size();
    }
    /**
     * <pre>
     * "list(double)"
     * </pre>
     *
     * <code>repeated double f = 5 [packed = true];</code>
     */
    public double getF(int index) {
      return f_.get(index);
    }
    private int fMemoizedSerializedSize = -1;

    public static final int B_FIELD_NUMBER = 6;
    private java.util.List<java.lang.Boolean> b_;
    /**
     * <pre>
     * "list(bool)"
     * </pre>
     *
     * <code>repeated bool b = 6 [packed = true];</code>
     */
    public java.util.List<java.lang.Boolean>
        getBList() {
      return b_;
    }
    /**
     * <pre>
     * "list(bool)"
     * </pre>
     *
     * <code>repeated bool b = 6 [packed = true];</code>
     */
    public int getBCount() {
      return b_.size();
    }
    /**
     * <pre>
     * "list(bool)"
     * </pre>
     *
     * <code>repeated bool b = 6 [packed = true];</code>
     */
    public boolean getB(int index) {
      return b_.get(index);
    }
    private int bMemoizedSerializedSize = -1;

    public static final int BB_FIELD_NUMBER = 7;
    private java.util.List<java.lang.Boolean> bb_;
    /**
     * <code>repeated bool bb = 7 [packed = true];</code>
     */
    public java.util.List<java.lang.Boolean>
        getBbList() {
      return bb_;
    }
    /**
     * <code>repeated bool bb = 7 [packed = true];</code>
     */
    public int getBbCount() {
      return bb_.size();
    }
    /**
     * <code>repeated bool bb = 7 [packed = true];</code>
     */
    public boolean getBb(int index) {
      return bb_.get(index);
    }
    private int bbMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < s_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, s_.getRaw(i));
      }
      if (getIList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(iMemoizedSerializedSize);
      }
      for (int i = 0; i < i_.size(); i++) {
        output.writeInt64NoTag(i_.get(i));
      }
      if (getCList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(cMemoizedSerializedSize);
      }
      for (int i = 0; i < c_.size(); i++) {
        output.writeFloatNoTag(c_.get(i));
      }
      if (getFList().size() > 0) {
        output.writeUInt32NoTag(42);
        output.writeUInt32NoTag(fMemoizedSerializedSize);
      }
      for (int i = 0; i < f_.size(); i++) {
        output.writeDoubleNoTag(f_.get(i));
      }
      if (getBList().size() > 0) {
        output.writeUInt32NoTag(50);
        output.writeUInt32NoTag(bMemoizedSerializedSize);
      }
      for (int i = 0; i < b_.size(); i++) {
        output.writeBoolNoTag(b_.get(i));
      }
      if (getBbList().size() > 0) {
        output.writeUInt32NoTag(58);
        output.writeUInt32NoTag(bbMemoizedSerializedSize);
      }
      for (int i = 0; i < bb_.size(); i++) {
        output.writeBoolNoTag(bb_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < s_.size(); i++) {
          dataSize += computeStringSizeNoTag(s_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < i_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(i_.get(i));
        }
        size += dataSize;
        if (!getIList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        iMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 4 * getCList().size();
        size += dataSize;
        if (!getCList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        cMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 8 * getFList().size();
        size += dataSize;
        if (!getFList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        fMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 1 * getBList().size();
        size += dataSize;
        if (!getBList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        bMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 1 * getBbList().size();
        size += dataSize;
        if (!getBbList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        bbMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ai.h2o.deepwater.backends.grpc.ParamValue.ListValue)) {
        return super.equals(obj);
      }
      ai.h2o.deepwater.backends.grpc.ParamValue.ListValue other = (ai.h2o.deepwater.backends.grpc.ParamValue.ListValue) obj;

      boolean result = true;
      result = result && getSList()
          .equals(other.getSList());
      result = result && getIList()
          .equals(other.getIList());
      result = result && getCList()
          .equals(other.getCList());
      result = result && getFList()
          .equals(other.getFList());
      result = result && getBList()
          .equals(other.getBList());
      result = result && getBbList()
          .equals(other.getBbList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getSCount() > 0) {
        hash = (37 * hash) + S_FIELD_NUMBER;
        hash = (53 * hash) + getSList().hashCode();
      }
      if (getICount() > 0) {
        hash = (37 * hash) + I_FIELD_NUMBER;
        hash = (53 * hash) + getIList().hashCode();
      }
      if (getCCount() > 0) {
        hash = (37 * hash) + C_FIELD_NUMBER;
        hash = (53 * hash) + getCList().hashCode();
      }
      if (getFCount() > 0) {
        hash = (37 * hash) + F_FIELD_NUMBER;
        hash = (53 * hash) + getFList().hashCode();
      }
      if (getBCount() > 0) {
        hash = (37 * hash) + B_FIELD_NUMBER;
        hash = (53 * hash) + getBList().hashCode();
      }
      if (getBbCount() > 0) {
        hash = (37 * hash) + BB_FIELD_NUMBER;
        hash = (53 * hash) + getBbList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ai.h2o.deepwater.backends.grpc.ParamValue.ListValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ai.h2o.deepwater.backends.grpc.ParamValue.ListValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ai.h2o.deepwater.backends.grpc.ParamValue.ListValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ai.h2o.deepwater.backends.grpc.ParamValue.ListValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ai.h2o.deepwater.backends.grpc.ParamValue.ListValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ai.h2o.deepwater.backends.grpc.ParamValue.ListValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ai.h2o.deepwater.backends.grpc.ParamValue.ListValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ai.h2o.deepwater.backends.grpc.ParamValue.ListValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ai.h2o.deepwater.backends.grpc.ParamValue.ListValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ai.h2o.deepwater.backends.grpc.ParamValue.ListValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ai.h2o.deepwater.backends.grpc.ParamValue.ListValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code deepwater.ParamValue.ListValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:deepwater.ParamValue.ListValue)
        ai.h2o.deepwater.backends.grpc.ParamValue.ListValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ai.h2o.deepwater.backends.grpc.DeepWaterGRPCService.internal_static_deepwater_ParamValue_ListValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ai.h2o.deepwater.backends.grpc.DeepWaterGRPCService.internal_static_deepwater_ParamValue_ListValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.class, ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.Builder.class);
      }

      // Construct using ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        s_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        i_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        c_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        f_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        b_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        bb_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ai.h2o.deepwater.backends.grpc.DeepWaterGRPCService.internal_static_deepwater_ParamValue_ListValue_descriptor;
      }

      public ai.h2o.deepwater.backends.grpc.ParamValue.ListValue getDefaultInstanceForType() {
        return ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.getDefaultInstance();
      }

      public ai.h2o.deepwater.backends.grpc.ParamValue.ListValue build() {
        ai.h2o.deepwater.backends.grpc.ParamValue.ListValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ai.h2o.deepwater.backends.grpc.ParamValue.ListValue buildPartial() {
        ai.h2o.deepwater.backends.grpc.ParamValue.ListValue result = new ai.h2o.deepwater.backends.grpc.ParamValue.ListValue(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          s_ = s_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.s_ = s_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          i_ = java.util.Collections.unmodifiableList(i_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.i_ = i_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          c_ = java.util.Collections.unmodifiableList(c_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.c_ = c_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          f_ = java.util.Collections.unmodifiableList(f_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.f_ = f_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          b_ = java.util.Collections.unmodifiableList(b_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.b_ = b_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          bb_ = java.util.Collections.unmodifiableList(bb_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.bb_ = bb_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ai.h2o.deepwater.backends.grpc.ParamValue.ListValue) {
          return mergeFrom((ai.h2o.deepwater.backends.grpc.ParamValue.ListValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ai.h2o.deepwater.backends.grpc.ParamValue.ListValue other) {
        if (other == ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.getDefaultInstance()) return this;
        if (!other.s_.isEmpty()) {
          if (s_.isEmpty()) {
            s_ = other.s_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSIsMutable();
            s_.addAll(other.s_);
          }
          onChanged();
        }
        if (!other.i_.isEmpty()) {
          if (i_.isEmpty()) {
            i_ = other.i_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureIIsMutable();
            i_.addAll(other.i_);
          }
          onChanged();
        }
        if (!other.c_.isEmpty()) {
          if (c_.isEmpty()) {
            c_ = other.c_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureCIsMutable();
            c_.addAll(other.c_);
          }
          onChanged();
        }
        if (!other.f_.isEmpty()) {
          if (f_.isEmpty()) {
            f_ = other.f_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureFIsMutable();
            f_.addAll(other.f_);
          }
          onChanged();
        }
        if (!other.b_.isEmpty()) {
          if (b_.isEmpty()) {
            b_ = other.b_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureBIsMutable();
            b_.addAll(other.b_);
          }
          onChanged();
        }
        if (!other.bb_.isEmpty()) {
          if (bb_.isEmpty()) {
            bb_ = other.bb_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureBbIsMutable();
            bb_.addAll(other.bb_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ai.h2o.deepwater.backends.grpc.ParamValue.ListValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ai.h2o.deepwater.backends.grpc.ParamValue.ListValue) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList s_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          s_ = new com.google.protobuf.LazyStringArrayList(s_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * "list(string)"
       * </pre>
       *
       * <code>repeated string s = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSList() {
        return s_.getUnmodifiableView();
      }
      /**
       * <pre>
       * "list(string)"
       * </pre>
       *
       * <code>repeated string s = 2;</code>
       */
      public int getSCount() {
        return s_.size();
      }
      /**
       * <pre>
       * "list(string)"
       * </pre>
       *
       * <code>repeated string s = 2;</code>
       */
      public java.lang.String getS(int index) {
        return s_.get(index);
      }
      /**
       * <pre>
       * "list(string)"
       * </pre>
       *
       * <code>repeated string s = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSBytes(int index) {
        return s_.getByteString(index);
      }
      /**
       * <pre>
       * "list(string)"
       * </pre>
       *
       * <code>repeated string s = 2;</code>
       */
      public Builder setS(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSIsMutable();
        s_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "list(string)"
       * </pre>
       *
       * <code>repeated string s = 2;</code>
       */
      public Builder addS(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSIsMutable();
        s_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "list(string)"
       * </pre>
       *
       * <code>repeated string s = 2;</code>
       */
      public Builder addAllS(
          java.lang.Iterable<java.lang.String> values) {
        ensureSIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, s_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "list(string)"
       * </pre>
       *
       * <code>repeated string s = 2;</code>
       */
      public Builder clearS() {
        s_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "list(string)"
       * </pre>
       *
       * <code>repeated string s = 2;</code>
       */
      public Builder addSBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSIsMutable();
        s_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Long> i_ = java.util.Collections.emptyList();
      private void ensureIIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          i_ = new java.util.ArrayList<java.lang.Long>(i_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       * "list(int)"
       * </pre>
       *
       * <code>repeated int64 i = 3 [packed = true];</code>
       */
      public java.util.List<java.lang.Long>
          getIList() {
        return java.util.Collections.unmodifiableList(i_);
      }
      /**
       * <pre>
       * "list(int)"
       * </pre>
       *
       * <code>repeated int64 i = 3 [packed = true];</code>
       */
      public int getICount() {
        return i_.size();
      }
      /**
       * <pre>
       * "list(int)"
       * </pre>
       *
       * <code>repeated int64 i = 3 [packed = true];</code>
       */
      public long getI(int index) {
        return i_.get(index);
      }
      /**
       * <pre>
       * "list(int)"
       * </pre>
       *
       * <code>repeated int64 i = 3 [packed = true];</code>
       */
      public Builder setI(
          int index, long value) {
        ensureIIsMutable();
        i_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "list(int)"
       * </pre>
       *
       * <code>repeated int64 i = 3 [packed = true];</code>
       */
      public Builder addI(long value) {
        ensureIIsMutable();
        i_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "list(int)"
       * </pre>
       *
       * <code>repeated int64 i = 3 [packed = true];</code>
       */
      public Builder addAllI(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureIIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, i_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "list(int)"
       * </pre>
       *
       * <code>repeated int64 i = 3 [packed = true];</code>
       */
      public Builder clearI() {
        i_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Float> c_ = java.util.Collections.emptyList();
      private void ensureCIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          c_ = new java.util.ArrayList<java.lang.Float>(c_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       * "list(float)"
       * </pre>
       *
       * <code>repeated float c = 4 [packed = true];</code>
       */
      public java.util.List<java.lang.Float>
          getCList() {
        return java.util.Collections.unmodifiableList(c_);
      }
      /**
       * <pre>
       * "list(float)"
       * </pre>
       *
       * <code>repeated float c = 4 [packed = true];</code>
       */
      public int getCCount() {
        return c_.size();
      }
      /**
       * <pre>
       * "list(float)"
       * </pre>
       *
       * <code>repeated float c = 4 [packed = true];</code>
       */
      public float getC(int index) {
        return c_.get(index);
      }
      /**
       * <pre>
       * "list(float)"
       * </pre>
       *
       * <code>repeated float c = 4 [packed = true];</code>
       */
      public Builder setC(
          int index, float value) {
        ensureCIsMutable();
        c_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "list(float)"
       * </pre>
       *
       * <code>repeated float c = 4 [packed = true];</code>
       */
      public Builder addC(float value) {
        ensureCIsMutable();
        c_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "list(float)"
       * </pre>
       *
       * <code>repeated float c = 4 [packed = true];</code>
       */
      public Builder addAllC(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureCIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, c_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "list(float)"
       * </pre>
       *
       * <code>repeated float c = 4 [packed = true];</code>
       */
      public Builder clearC() {
        c_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Double> f_ = java.util.Collections.emptyList();
      private void ensureFIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          f_ = new java.util.ArrayList<java.lang.Double>(f_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <pre>
       * "list(double)"
       * </pre>
       *
       * <code>repeated double f = 5 [packed = true];</code>
       */
      public java.util.List<java.lang.Double>
          getFList() {
        return java.util.Collections.unmodifiableList(f_);
      }
      /**
       * <pre>
       * "list(double)"
       * </pre>
       *
       * <code>repeated double f = 5 [packed = true];</code>
       */
      public int getFCount() {
        return f_.size();
      }
      /**
       * <pre>
       * "list(double)"
       * </pre>
       *
       * <code>repeated double f = 5 [packed = true];</code>
       */
      public double getF(int index) {
        return f_.get(index);
      }
      /**
       * <pre>
       * "list(double)"
       * </pre>
       *
       * <code>repeated double f = 5 [packed = true];</code>
       */
      public Builder setF(
          int index, double value) {
        ensureFIsMutable();
        f_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "list(double)"
       * </pre>
       *
       * <code>repeated double f = 5 [packed = true];</code>
       */
      public Builder addF(double value) {
        ensureFIsMutable();
        f_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "list(double)"
       * </pre>
       *
       * <code>repeated double f = 5 [packed = true];</code>
       */
      public Builder addAllF(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureFIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, f_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "list(double)"
       * </pre>
       *
       * <code>repeated double f = 5 [packed = true];</code>
       */
      public Builder clearF() {
        f_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Boolean> b_ = java.util.Collections.emptyList();
      private void ensureBIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          b_ = new java.util.ArrayList<java.lang.Boolean>(b_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <pre>
       * "list(bool)"
       * </pre>
       *
       * <code>repeated bool b = 6 [packed = true];</code>
       */
      public java.util.List<java.lang.Boolean>
          getBList() {
        return java.util.Collections.unmodifiableList(b_);
      }
      /**
       * <pre>
       * "list(bool)"
       * </pre>
       *
       * <code>repeated bool b = 6 [packed = true];</code>
       */
      public int getBCount() {
        return b_.size();
      }
      /**
       * <pre>
       * "list(bool)"
       * </pre>
       *
       * <code>repeated bool b = 6 [packed = true];</code>
       */
      public boolean getB(int index) {
        return b_.get(index);
      }
      /**
       * <pre>
       * "list(bool)"
       * </pre>
       *
       * <code>repeated bool b = 6 [packed = true];</code>
       */
      public Builder setB(
          int index, boolean value) {
        ensureBIsMutable();
        b_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "list(bool)"
       * </pre>
       *
       * <code>repeated bool b = 6 [packed = true];</code>
       */
      public Builder addB(boolean value) {
        ensureBIsMutable();
        b_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "list(bool)"
       * </pre>
       *
       * <code>repeated bool b = 6 [packed = true];</code>
       */
      public Builder addAllB(
          java.lang.Iterable<? extends java.lang.Boolean> values) {
        ensureBIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, b_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "list(bool)"
       * </pre>
       *
       * <code>repeated bool b = 6 [packed = true];</code>
       */
      public Builder clearB() {
        b_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Boolean> bb_ = java.util.Collections.emptyList();
      private void ensureBbIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          bb_ = new java.util.ArrayList<java.lang.Boolean>(bb_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated bool bb = 7 [packed = true];</code>
       */
      public java.util.List<java.lang.Boolean>
          getBbList() {
        return java.util.Collections.unmodifiableList(bb_);
      }
      /**
       * <code>repeated bool bb = 7 [packed = true];</code>
       */
      public int getBbCount() {
        return bb_.size();
      }
      /**
       * <code>repeated bool bb = 7 [packed = true];</code>
       */
      public boolean getBb(int index) {
        return bb_.get(index);
      }
      /**
       * <code>repeated bool bb = 7 [packed = true];</code>
       */
      public Builder setBb(
          int index, boolean value) {
        ensureBbIsMutable();
        bb_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool bb = 7 [packed = true];</code>
       */
      public Builder addBb(boolean value) {
        ensureBbIsMutable();
        bb_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool bb = 7 [packed = true];</code>
       */
      public Builder addAllBb(
          java.lang.Iterable<? extends java.lang.Boolean> values) {
        ensureBbIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bb_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool bb = 7 [packed = true];</code>
       */
      public Builder clearBb() {
        bb_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:deepwater.ParamValue.ListValue)
    }

    // @@protoc_insertion_point(class_scope:deepwater.ParamValue.ListValue)
    private static final ai.h2o.deepwater.backends.grpc.ParamValue.ListValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ai.h2o.deepwater.backends.grpc.ParamValue.ListValue();
    }

    public static ai.h2o.deepwater.backends.grpc.ParamValue.ListValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListValue>
        PARSER = new com.google.protobuf.AbstractParser<ListValue>() {
      public ListValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ListValue(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ListValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListValue> getParserForType() {
      return PARSER;
    }

    public ai.h2o.deepwater.backends.grpc.ParamValue.ListValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int valueCase_ = 0;
  private java.lang.Object value_;
  public enum ValueCase
      implements com.google.protobuf.Internal.EnumLite {
    S(2),
    I(3),
    F(4),
    D(5),
    B(6),
    BB(7),
    LIST(1),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 2: return S;
        case 3: return I;
        case 4: return F;
        case 5: return D;
        case 6: return B;
        case 7: return BB;
        case 1: return LIST;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  public static final int S_FIELD_NUMBER = 2;
  /**
   * <pre>
   * "string"
   * </pre>
   *
   * <code>optional string s = 2;</code>
   */
  public java.lang.String getS() {
    java.lang.Object ref = "";
    if (valueCase_ == 2) {
      ref = value_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (valueCase_ == 2) {
        value_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * "string"
   * </pre>
   *
   * <code>optional string s = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSBytes() {
    java.lang.Object ref = "";
    if (valueCase_ == 2) {
      ref = value_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (valueCase_ == 2) {
        value_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int I_FIELD_NUMBER = 3;
  /**
   * <pre>
   * "int"
   * </pre>
   *
   * <code>optional int64 i = 3;</code>
   */
  public long getI() {
    if (valueCase_ == 3) {
      return (java.lang.Long) value_;
    }
    return 0L;
  }

  public static final int F_FIELD_NUMBER = 4;
  /**
   * <pre>
   * "float"
   * </pre>
   *
   * <code>optional float f = 4;</code>
   */
  public float getF() {
    if (valueCase_ == 4) {
      return (java.lang.Float) value_;
    }
    return 0F;
  }

  public static final int D_FIELD_NUMBER = 5;
  /**
   * <pre>
   * "float"
   * </pre>
   *
   * <code>optional double d = 5;</code>
   */
  public double getD() {
    if (valueCase_ == 5) {
      return (java.lang.Double) value_;
    }
    return 0D;
  }

  public static final int B_FIELD_NUMBER = 6;
  /**
   * <pre>
   * "bool"
   * </pre>
   *
   * <code>optional bool b = 6;</code>
   */
  public boolean getB() {
    if (valueCase_ == 6) {
      return (java.lang.Boolean) value_;
    }
    return false;
  }

  public static final int BB_FIELD_NUMBER = 7;
  /**
   * <pre>
   * "string"
   * </pre>
   *
   * <code>optional bytes bb = 7;</code>
   */
  public com.google.protobuf.ByteString getBb() {
    if (valueCase_ == 7) {
      return (com.google.protobuf.ByteString) value_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int LIST_FIELD_NUMBER = 1;
  /**
   * <pre>
   * any "list(...)"
   * </pre>
   *
   * <code>optional .deepwater.ParamValue.ListValue list = 1;</code>
   */
  public ai.h2o.deepwater.backends.grpc.ParamValue.ListValue getList() {
    if (valueCase_ == 1) {
       return (ai.h2o.deepwater.backends.grpc.ParamValue.ListValue) value_;
    }
    return ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.getDefaultInstance();
  }
  /**
   * <pre>
   * any "list(...)"
   * </pre>
   *
   * <code>optional .deepwater.ParamValue.ListValue list = 1;</code>
   */
  public ai.h2o.deepwater.backends.grpc.ParamValue.ListValueOrBuilder getListOrBuilder() {
    if (valueCase_ == 1) {
       return (ai.h2o.deepwater.backends.grpc.ParamValue.ListValue) value_;
    }
    return ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (valueCase_ == 1) {
      output.writeMessage(1, (ai.h2o.deepwater.backends.grpc.ParamValue.ListValue) value_);
    }
    if (valueCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
    }
    if (valueCase_ == 3) {
      output.writeInt64(
          3, (long)((java.lang.Long) value_));
    }
    if (valueCase_ == 4) {
      output.writeFloat(
          4, (float)((java.lang.Float) value_));
    }
    if (valueCase_ == 5) {
      output.writeDouble(
          5, (double)((java.lang.Double) value_));
    }
    if (valueCase_ == 6) {
      output.writeBool(
          6, (boolean)((java.lang.Boolean) value_));
    }
    if (valueCase_ == 7) {
      output.writeBytes(
          7, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) value_));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (valueCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (ai.h2o.deepwater.backends.grpc.ParamValue.ListValue) value_);
    }
    if (valueCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
    }
    if (valueCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(
            3, (long)((java.lang.Long) value_));
    }
    if (valueCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(
            4, (float)((java.lang.Float) value_));
    }
    if (valueCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(
            5, (double)((java.lang.Double) value_));
    }
    if (valueCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            6, (boolean)((java.lang.Boolean) value_));
    }
    if (valueCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            7, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) value_));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.h2o.deepwater.backends.grpc.ParamValue)) {
      return super.equals(obj);
    }
    ai.h2o.deepwater.backends.grpc.ParamValue other = (ai.h2o.deepwater.backends.grpc.ParamValue) obj;

    boolean result = true;
    result = result && getValueCase().equals(
        other.getValueCase());
    if (!result) return false;
    switch (valueCase_) {
      case 2:
        result = result && getS()
            .equals(other.getS());
        break;
      case 3:
        result = result && (getI()
            == other.getI());
        break;
      case 4:
        result = result && (
            java.lang.Float.floatToIntBits(getF())
            == java.lang.Float.floatToIntBits(
                other.getF()));
        break;
      case 5:
        result = result && (
            java.lang.Double.doubleToLongBits(getD())
            == java.lang.Double.doubleToLongBits(
                other.getD()));
        break;
      case 6:
        result = result && (getB()
            == other.getB());
        break;
      case 7:
        result = result && getBb()
            .equals(other.getBb());
        break;
      case 1:
        result = result && getList()
            .equals(other.getList());
        break;
      case 0:
      default:
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    switch (valueCase_) {
      case 2:
        hash = (37 * hash) + S_FIELD_NUMBER;
        hash = (53 * hash) + getS().hashCode();
        break;
      case 3:
        hash = (37 * hash) + I_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getI());
        break;
      case 4:
        hash = (37 * hash) + F_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getF());
        break;
      case 5:
        hash = (37 * hash) + D_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getD()));
        break;
      case 6:
        hash = (37 * hash) + B_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getB());
        break;
      case 7:
        hash = (37 * hash) + BB_FIELD_NUMBER;
        hash = (53 * hash) + getBb().hashCode();
        break;
      case 1:
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getList().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.h2o.deepwater.backends.grpc.ParamValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.h2o.deepwater.backends.grpc.ParamValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.h2o.deepwater.backends.grpc.ParamValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.h2o.deepwater.backends.grpc.ParamValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.h2o.deepwater.backends.grpc.ParamValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.h2o.deepwater.backends.grpc.ParamValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.h2o.deepwater.backends.grpc.ParamValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ai.h2o.deepwater.backends.grpc.ParamValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.h2o.deepwater.backends.grpc.ParamValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.h2o.deepwater.backends.grpc.ParamValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.h2o.deepwater.backends.grpc.ParamValue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code deepwater.ParamValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:deepwater.ParamValue)
      ai.h2o.deepwater.backends.grpc.ParamValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.h2o.deepwater.backends.grpc.DeepWaterGRPCService.internal_static_deepwater_ParamValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.h2o.deepwater.backends.grpc.DeepWaterGRPCService.internal_static_deepwater_ParamValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.h2o.deepwater.backends.grpc.ParamValue.class, ai.h2o.deepwater.backends.grpc.ParamValue.Builder.class);
    }

    // Construct using ai.h2o.deepwater.backends.grpc.ParamValue.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      valueCase_ = 0;
      value_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.h2o.deepwater.backends.grpc.DeepWaterGRPCService.internal_static_deepwater_ParamValue_descriptor;
    }

    public ai.h2o.deepwater.backends.grpc.ParamValue getDefaultInstanceForType() {
      return ai.h2o.deepwater.backends.grpc.ParamValue.getDefaultInstance();
    }

    public ai.h2o.deepwater.backends.grpc.ParamValue build() {
      ai.h2o.deepwater.backends.grpc.ParamValue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ai.h2o.deepwater.backends.grpc.ParamValue buildPartial() {
      ai.h2o.deepwater.backends.grpc.ParamValue result = new ai.h2o.deepwater.backends.grpc.ParamValue(this);
      if (valueCase_ == 2) {
        result.value_ = value_;
      }
      if (valueCase_ == 3) {
        result.value_ = value_;
      }
      if (valueCase_ == 4) {
        result.value_ = value_;
      }
      if (valueCase_ == 5) {
        result.value_ = value_;
      }
      if (valueCase_ == 6) {
        result.value_ = value_;
      }
      if (valueCase_ == 7) {
        result.value_ = value_;
      }
      if (valueCase_ == 1) {
        if (listBuilder_ == null) {
          result.value_ = value_;
        } else {
          result.value_ = listBuilder_.build();
        }
      }
      result.valueCase_ = valueCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.h2o.deepwater.backends.grpc.ParamValue) {
        return mergeFrom((ai.h2o.deepwater.backends.grpc.ParamValue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.h2o.deepwater.backends.grpc.ParamValue other) {
      if (other == ai.h2o.deepwater.backends.grpc.ParamValue.getDefaultInstance()) return this;
      switch (other.getValueCase()) {
        case S: {
          valueCase_ = 2;
          value_ = other.value_;
          onChanged();
          break;
        }
        case I: {
          setI(other.getI());
          break;
        }
        case F: {
          setF(other.getF());
          break;
        }
        case D: {
          setD(other.getD());
          break;
        }
        case B: {
          setB(other.getB());
          break;
        }
        case BB: {
          setBb(other.getBb());
          break;
        }
        case LIST: {
          mergeList(other.getList());
          break;
        }
        case VALUE_NOT_SET: {
          break;
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.h2o.deepwater.backends.grpc.ParamValue parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.h2o.deepwater.backends.grpc.ParamValue) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int valueCase_ = 0;
    private java.lang.Object value_;
    public ValueCase
        getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public Builder clearValue() {
      valueCase_ = 0;
      value_ = null;
      onChanged();
      return this;
    }


    /**
     * <pre>
     * "string"
     * </pre>
     *
     * <code>optional string s = 2;</code>
     */
    public java.lang.String getS() {
      java.lang.Object ref = "";
      if (valueCase_ == 2) {
        ref = value_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valueCase_ == 2) {
          value_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "string"
     * </pre>
     *
     * <code>optional string s = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSBytes() {
      java.lang.Object ref = "";
      if (valueCase_ == 2) {
        ref = value_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueCase_ == 2) {
          value_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "string"
     * </pre>
     *
     * <code>optional string s = 2;</code>
     */
    public Builder setS(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 2;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "string"
     * </pre>
     *
     * <code>optional string s = 2;</code>
     */
    public Builder clearS() {
      if (valueCase_ == 2) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * "string"
     * </pre>
     *
     * <code>optional string s = 2;</code>
     */
    public Builder setSBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      valueCase_ = 2;
      value_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * "int"
     * </pre>
     *
     * <code>optional int64 i = 3;</code>
     */
    public long getI() {
      if (valueCase_ == 3) {
        return (java.lang.Long) value_;
      }
      return 0L;
    }
    /**
     * <pre>
     * "int"
     * </pre>
     *
     * <code>optional int64 i = 3;</code>
     */
    public Builder setI(long value) {
      valueCase_ = 3;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "int"
     * </pre>
     *
     * <code>optional int64 i = 3;</code>
     */
    public Builder clearI() {
      if (valueCase_ == 3) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * "float"
     * </pre>
     *
     * <code>optional float f = 4;</code>
     */
    public float getF() {
      if (valueCase_ == 4) {
        return (java.lang.Float) value_;
      }
      return 0F;
    }
    /**
     * <pre>
     * "float"
     * </pre>
     *
     * <code>optional float f = 4;</code>
     */
    public Builder setF(float value) {
      valueCase_ = 4;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "float"
     * </pre>
     *
     * <code>optional float f = 4;</code>
     */
    public Builder clearF() {
      if (valueCase_ == 4) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * "float"
     * </pre>
     *
     * <code>optional double d = 5;</code>
     */
    public double getD() {
      if (valueCase_ == 5) {
        return (java.lang.Double) value_;
      }
      return 0D;
    }
    /**
     * <pre>
     * "float"
     * </pre>
     *
     * <code>optional double d = 5;</code>
     */
    public Builder setD(double value) {
      valueCase_ = 5;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "float"
     * </pre>
     *
     * <code>optional double d = 5;</code>
     */
    public Builder clearD() {
      if (valueCase_ == 5) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * "bool"
     * </pre>
     *
     * <code>optional bool b = 6;</code>
     */
    public boolean getB() {
      if (valueCase_ == 6) {
        return (java.lang.Boolean) value_;
      }
      return false;
    }
    /**
     * <pre>
     * "bool"
     * </pre>
     *
     * <code>optional bool b = 6;</code>
     */
    public Builder setB(boolean value) {
      valueCase_ = 6;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "bool"
     * </pre>
     *
     * <code>optional bool b = 6;</code>
     */
    public Builder clearB() {
      if (valueCase_ == 6) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * "string"
     * </pre>
     *
     * <code>optional bytes bb = 7;</code>
     */
    public com.google.protobuf.ByteString getBb() {
      if (valueCase_ == 7) {
        return (com.google.protobuf.ByteString) value_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     * "string"
     * </pre>
     *
     * <code>optional bytes bb = 7;</code>
     */
    public Builder setBb(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 7;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "string"
     * </pre>
     *
     * <code>optional bytes bb = 7;</code>
     */
    public Builder clearBb() {
      if (valueCase_ == 7) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ai.h2o.deepwater.backends.grpc.ParamValue.ListValue, ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.Builder, ai.h2o.deepwater.backends.grpc.ParamValue.ListValueOrBuilder> listBuilder_;
    /**
     * <pre>
     * any "list(...)"
     * </pre>
     *
     * <code>optional .deepwater.ParamValue.ListValue list = 1;</code>
     */
    public ai.h2o.deepwater.backends.grpc.ParamValue.ListValue getList() {
      if (listBuilder_ == null) {
        if (valueCase_ == 1) {
          return (ai.h2o.deepwater.backends.grpc.ParamValue.ListValue) value_;
        }
        return ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.getDefaultInstance();
      } else {
        if (valueCase_ == 1) {
          return listBuilder_.getMessage();
        }
        return ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * any "list(...)"
     * </pre>
     *
     * <code>optional .deepwater.ParamValue.ListValue list = 1;</code>
     */
    public Builder setList(ai.h2o.deepwater.backends.grpc.ParamValue.ListValue value) {
      if (listBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        listBuilder_.setMessage(value);
      }
      valueCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * any "list(...)"
     * </pre>
     *
     * <code>optional .deepwater.ParamValue.ListValue list = 1;</code>
     */
    public Builder setList(
        ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.Builder builderForValue) {
      if (listBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        listBuilder_.setMessage(builderForValue.build());
      }
      valueCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * any "list(...)"
     * </pre>
     *
     * <code>optional .deepwater.ParamValue.ListValue list = 1;</code>
     */
    public Builder mergeList(ai.h2o.deepwater.backends.grpc.ParamValue.ListValue value) {
      if (listBuilder_ == null) {
        if (valueCase_ == 1 &&
            value_ != ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.getDefaultInstance()) {
          value_ = ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.newBuilder((ai.h2o.deepwater.backends.grpc.ParamValue.ListValue) value_)
              .mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        if (valueCase_ == 1) {
          listBuilder_.mergeFrom(value);
        }
        listBuilder_.setMessage(value);
      }
      valueCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * any "list(...)"
     * </pre>
     *
     * <code>optional .deepwater.ParamValue.ListValue list = 1;</code>
     */
    public Builder clearList() {
      if (listBuilder_ == null) {
        if (valueCase_ == 1) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
      } else {
        if (valueCase_ == 1) {
          valueCase_ = 0;
          value_ = null;
        }
        listBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * any "list(...)"
     * </pre>
     *
     * <code>optional .deepwater.ParamValue.ListValue list = 1;</code>
     */
    public ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.Builder getListBuilder() {
      return getListFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * any "list(...)"
     * </pre>
     *
     * <code>optional .deepwater.ParamValue.ListValue list = 1;</code>
     */
    public ai.h2o.deepwater.backends.grpc.ParamValue.ListValueOrBuilder getListOrBuilder() {
      if ((valueCase_ == 1) && (listBuilder_ != null)) {
        return listBuilder_.getMessageOrBuilder();
      } else {
        if (valueCase_ == 1) {
          return (ai.h2o.deepwater.backends.grpc.ParamValue.ListValue) value_;
        }
        return ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * any "list(...)"
     * </pre>
     *
     * <code>optional .deepwater.ParamValue.ListValue list = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.h2o.deepwater.backends.grpc.ParamValue.ListValue, ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.Builder, ai.h2o.deepwater.backends.grpc.ParamValue.ListValueOrBuilder> 
        getListFieldBuilder() {
      if (listBuilder_ == null) {
        if (!(valueCase_ == 1)) {
          value_ = ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.getDefaultInstance();
        }
        listBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.h2o.deepwater.backends.grpc.ParamValue.ListValue, ai.h2o.deepwater.backends.grpc.ParamValue.ListValue.Builder, ai.h2o.deepwater.backends.grpc.ParamValue.ListValueOrBuilder>(
                (ai.h2o.deepwater.backends.grpc.ParamValue.ListValue) value_,
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      valueCase_ = 1;
      onChanged();;
      return listBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:deepwater.ParamValue)
  }

  // @@protoc_insertion_point(class_scope:deepwater.ParamValue)
  private static final ai.h2o.deepwater.backends.grpc.ParamValue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.h2o.deepwater.backends.grpc.ParamValue();
  }

  public static ai.h2o.deepwater.backends.grpc.ParamValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ParamValue>
      PARSER = new com.google.protobuf.AbstractParser<ParamValue>() {
    public ParamValue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ParamValue(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ParamValue> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ParamValue> getParserForType() {
    return PARSER;
  }

  public ai.h2o.deepwater.backends.grpc.ParamValue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

