// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_service.proto

package ai.h2o.deepwater.backends.grpc;

/**
 * Protobuf type {@code deepwater.TrainResponse}
 */
public  final class TrainResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:deepwater.TrainResponse)
    TrainResponseOrBuilder {
  // Use TrainResponse.newBuilder() to construct.
  private TrainResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrainResponse() {
    fetches_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TrainResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            ai.h2o.deepwater.backends.grpc.BackendModel.Builder subBuilder = null;
            if (model_ != null) {
              subBuilder = model_.toBuilder();
            }
            model_ = input.readMessage(ai.h2o.deepwater.backends.grpc.BackendModel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(model_);
              model_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              fetches_ = new java.util.ArrayList<ai.h2o.deepwater.backends.grpc.Tensor>();
              mutable_bitField0_ |= 0x00000002;
            }
            fetches_.add(
                input.readMessage(ai.h2o.deepwater.backends.grpc.Tensor.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        fetches_ = java.util.Collections.unmodifiableList(fetches_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.h2o.deepwater.backends.grpc.DeepWaterGRPCService.internal_static_deepwater_TrainResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.h2o.deepwater.backends.grpc.DeepWaterGRPCService.internal_static_deepwater_TrainResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.h2o.deepwater.backends.grpc.TrainResponse.class, ai.h2o.deepwater.backends.grpc.TrainResponse.Builder.class);
  }

  private int bitField0_;
  public static final int MODEL_FIELD_NUMBER = 1;
  private ai.h2o.deepwater.backends.grpc.BackendModel model_;
  /**
   * <code>optional .deepwater.BackendModel model = 1;</code>
   */
  public boolean hasModel() {
    return model_ != null;
  }
  /**
   * <code>optional .deepwater.BackendModel model = 1;</code>
   */
  public ai.h2o.deepwater.backends.grpc.BackendModel getModel() {
    return model_ == null ? ai.h2o.deepwater.backends.grpc.BackendModel.getDefaultInstance() : model_;
  }
  /**
   * <code>optional .deepwater.BackendModel model = 1;</code>
   */
  public ai.h2o.deepwater.backends.grpc.BackendModelOrBuilder getModelOrBuilder() {
    return getModel();
  }

  public static final int FETCHES_FIELD_NUMBER = 3;
  private java.util.List<ai.h2o.deepwater.backends.grpc.Tensor> fetches_;
  /**
   * <code>repeated .deepwater.Tensor fetches = 3;</code>
   */
  public java.util.List<ai.h2o.deepwater.backends.grpc.Tensor> getFetchesList() {
    return fetches_;
  }
  /**
   * <code>repeated .deepwater.Tensor fetches = 3;</code>
   */
  public java.util.List<? extends ai.h2o.deepwater.backends.grpc.TensorOrBuilder> 
      getFetchesOrBuilderList() {
    return fetches_;
  }
  /**
   * <code>repeated .deepwater.Tensor fetches = 3;</code>
   */
  public int getFetchesCount() {
    return fetches_.size();
  }
  /**
   * <code>repeated .deepwater.Tensor fetches = 3;</code>
   */
  public ai.h2o.deepwater.backends.grpc.Tensor getFetches(int index) {
    return fetches_.get(index);
  }
  /**
   * <code>repeated .deepwater.Tensor fetches = 3;</code>
   */
  public ai.h2o.deepwater.backends.grpc.TensorOrBuilder getFetchesOrBuilder(
      int index) {
    return fetches_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (model_ != null) {
      output.writeMessage(1, getModel());
    }
    for (int i = 0; i < fetches_.size(); i++) {
      output.writeMessage(3, fetches_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (model_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getModel());
    }
    for (int i = 0; i < fetches_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, fetches_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.h2o.deepwater.backends.grpc.TrainResponse)) {
      return super.equals(obj);
    }
    ai.h2o.deepwater.backends.grpc.TrainResponse other = (ai.h2o.deepwater.backends.grpc.TrainResponse) obj;

    boolean result = true;
    result = result && (hasModel() == other.hasModel());
    if (hasModel()) {
      result = result && getModel()
          .equals(other.getModel());
    }
    result = result && getFetchesList()
        .equals(other.getFetchesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasModel()) {
      hash = (37 * hash) + MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getModel().hashCode();
    }
    if (getFetchesCount() > 0) {
      hash = (37 * hash) + FETCHES_FIELD_NUMBER;
      hash = (53 * hash) + getFetchesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.h2o.deepwater.backends.grpc.TrainResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.h2o.deepwater.backends.grpc.TrainResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.h2o.deepwater.backends.grpc.TrainResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.h2o.deepwater.backends.grpc.TrainResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.h2o.deepwater.backends.grpc.TrainResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.h2o.deepwater.backends.grpc.TrainResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.h2o.deepwater.backends.grpc.TrainResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ai.h2o.deepwater.backends.grpc.TrainResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.h2o.deepwater.backends.grpc.TrainResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.h2o.deepwater.backends.grpc.TrainResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.h2o.deepwater.backends.grpc.TrainResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code deepwater.TrainResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:deepwater.TrainResponse)
      ai.h2o.deepwater.backends.grpc.TrainResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.h2o.deepwater.backends.grpc.DeepWaterGRPCService.internal_static_deepwater_TrainResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.h2o.deepwater.backends.grpc.DeepWaterGRPCService.internal_static_deepwater_TrainResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.h2o.deepwater.backends.grpc.TrainResponse.class, ai.h2o.deepwater.backends.grpc.TrainResponse.Builder.class);
    }

    // Construct using ai.h2o.deepwater.backends.grpc.TrainResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFetchesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (modelBuilder_ == null) {
        model_ = null;
      } else {
        model_ = null;
        modelBuilder_ = null;
      }
      if (fetchesBuilder_ == null) {
        fetches_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        fetchesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.h2o.deepwater.backends.grpc.DeepWaterGRPCService.internal_static_deepwater_TrainResponse_descriptor;
    }

    public ai.h2o.deepwater.backends.grpc.TrainResponse getDefaultInstanceForType() {
      return ai.h2o.deepwater.backends.grpc.TrainResponse.getDefaultInstance();
    }

    public ai.h2o.deepwater.backends.grpc.TrainResponse build() {
      ai.h2o.deepwater.backends.grpc.TrainResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ai.h2o.deepwater.backends.grpc.TrainResponse buildPartial() {
      ai.h2o.deepwater.backends.grpc.TrainResponse result = new ai.h2o.deepwater.backends.grpc.TrainResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (modelBuilder_ == null) {
        result.model_ = model_;
      } else {
        result.model_ = modelBuilder_.build();
      }
      if (fetchesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          fetches_ = java.util.Collections.unmodifiableList(fetches_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.fetches_ = fetches_;
      } else {
        result.fetches_ = fetchesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.h2o.deepwater.backends.grpc.TrainResponse) {
        return mergeFrom((ai.h2o.deepwater.backends.grpc.TrainResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.h2o.deepwater.backends.grpc.TrainResponse other) {
      if (other == ai.h2o.deepwater.backends.grpc.TrainResponse.getDefaultInstance()) return this;
      if (other.hasModel()) {
        mergeModel(other.getModel());
      }
      if (fetchesBuilder_ == null) {
        if (!other.fetches_.isEmpty()) {
          if (fetches_.isEmpty()) {
            fetches_ = other.fetches_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFetchesIsMutable();
            fetches_.addAll(other.fetches_);
          }
          onChanged();
        }
      } else {
        if (!other.fetches_.isEmpty()) {
          if (fetchesBuilder_.isEmpty()) {
            fetchesBuilder_.dispose();
            fetchesBuilder_ = null;
            fetches_ = other.fetches_;
            bitField0_ = (bitField0_ & ~0x00000002);
            fetchesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFetchesFieldBuilder() : null;
          } else {
            fetchesBuilder_.addAllMessages(other.fetches_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.h2o.deepwater.backends.grpc.TrainResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.h2o.deepwater.backends.grpc.TrainResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private ai.h2o.deepwater.backends.grpc.BackendModel model_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.h2o.deepwater.backends.grpc.BackendModel, ai.h2o.deepwater.backends.grpc.BackendModel.Builder, ai.h2o.deepwater.backends.grpc.BackendModelOrBuilder> modelBuilder_;
    /**
     * <code>optional .deepwater.BackendModel model = 1;</code>
     */
    public boolean hasModel() {
      return modelBuilder_ != null || model_ != null;
    }
    /**
     * <code>optional .deepwater.BackendModel model = 1;</code>
     */
    public ai.h2o.deepwater.backends.grpc.BackendModel getModel() {
      if (modelBuilder_ == null) {
        return model_ == null ? ai.h2o.deepwater.backends.grpc.BackendModel.getDefaultInstance() : model_;
      } else {
        return modelBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .deepwater.BackendModel model = 1;</code>
     */
    public Builder setModel(ai.h2o.deepwater.backends.grpc.BackendModel value) {
      if (modelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        model_ = value;
        onChanged();
      } else {
        modelBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .deepwater.BackendModel model = 1;</code>
     */
    public Builder setModel(
        ai.h2o.deepwater.backends.grpc.BackendModel.Builder builderForValue) {
      if (modelBuilder_ == null) {
        model_ = builderForValue.build();
        onChanged();
      } else {
        modelBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .deepwater.BackendModel model = 1;</code>
     */
    public Builder mergeModel(ai.h2o.deepwater.backends.grpc.BackendModel value) {
      if (modelBuilder_ == null) {
        if (model_ != null) {
          model_ =
            ai.h2o.deepwater.backends.grpc.BackendModel.newBuilder(model_).mergeFrom(value).buildPartial();
        } else {
          model_ = value;
        }
        onChanged();
      } else {
        modelBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .deepwater.BackendModel model = 1;</code>
     */
    public Builder clearModel() {
      if (modelBuilder_ == null) {
        model_ = null;
        onChanged();
      } else {
        model_ = null;
        modelBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .deepwater.BackendModel model = 1;</code>
     */
    public ai.h2o.deepwater.backends.grpc.BackendModel.Builder getModelBuilder() {
      
      onChanged();
      return getModelFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .deepwater.BackendModel model = 1;</code>
     */
    public ai.h2o.deepwater.backends.grpc.BackendModelOrBuilder getModelOrBuilder() {
      if (modelBuilder_ != null) {
        return modelBuilder_.getMessageOrBuilder();
      } else {
        return model_ == null ?
            ai.h2o.deepwater.backends.grpc.BackendModel.getDefaultInstance() : model_;
      }
    }
    /**
     * <code>optional .deepwater.BackendModel model = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.h2o.deepwater.backends.grpc.BackendModel, ai.h2o.deepwater.backends.grpc.BackendModel.Builder, ai.h2o.deepwater.backends.grpc.BackendModelOrBuilder> 
        getModelFieldBuilder() {
      if (modelBuilder_ == null) {
        modelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.h2o.deepwater.backends.grpc.BackendModel, ai.h2o.deepwater.backends.grpc.BackendModel.Builder, ai.h2o.deepwater.backends.grpc.BackendModelOrBuilder>(
                getModel(),
                getParentForChildren(),
                isClean());
        model_ = null;
      }
      return modelBuilder_;
    }

    private java.util.List<ai.h2o.deepwater.backends.grpc.Tensor> fetches_ =
      java.util.Collections.emptyList();
    private void ensureFetchesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        fetches_ = new java.util.ArrayList<ai.h2o.deepwater.backends.grpc.Tensor>(fetches_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ai.h2o.deepwater.backends.grpc.Tensor, ai.h2o.deepwater.backends.grpc.Tensor.Builder, ai.h2o.deepwater.backends.grpc.TensorOrBuilder> fetchesBuilder_;

    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public java.util.List<ai.h2o.deepwater.backends.grpc.Tensor> getFetchesList() {
      if (fetchesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fetches_);
      } else {
        return fetchesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public int getFetchesCount() {
      if (fetchesBuilder_ == null) {
        return fetches_.size();
      } else {
        return fetchesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public ai.h2o.deepwater.backends.grpc.Tensor getFetches(int index) {
      if (fetchesBuilder_ == null) {
        return fetches_.get(index);
      } else {
        return fetchesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public Builder setFetches(
        int index, ai.h2o.deepwater.backends.grpc.Tensor value) {
      if (fetchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFetchesIsMutable();
        fetches_.set(index, value);
        onChanged();
      } else {
        fetchesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public Builder setFetches(
        int index, ai.h2o.deepwater.backends.grpc.Tensor.Builder builderForValue) {
      if (fetchesBuilder_ == null) {
        ensureFetchesIsMutable();
        fetches_.set(index, builderForValue.build());
        onChanged();
      } else {
        fetchesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public Builder addFetches(ai.h2o.deepwater.backends.grpc.Tensor value) {
      if (fetchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFetchesIsMutable();
        fetches_.add(value);
        onChanged();
      } else {
        fetchesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public Builder addFetches(
        int index, ai.h2o.deepwater.backends.grpc.Tensor value) {
      if (fetchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFetchesIsMutable();
        fetches_.add(index, value);
        onChanged();
      } else {
        fetchesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public Builder addFetches(
        ai.h2o.deepwater.backends.grpc.Tensor.Builder builderForValue) {
      if (fetchesBuilder_ == null) {
        ensureFetchesIsMutable();
        fetches_.add(builderForValue.build());
        onChanged();
      } else {
        fetchesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public Builder addFetches(
        int index, ai.h2o.deepwater.backends.grpc.Tensor.Builder builderForValue) {
      if (fetchesBuilder_ == null) {
        ensureFetchesIsMutable();
        fetches_.add(index, builderForValue.build());
        onChanged();
      } else {
        fetchesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public Builder addAllFetches(
        java.lang.Iterable<? extends ai.h2o.deepwater.backends.grpc.Tensor> values) {
      if (fetchesBuilder_ == null) {
        ensureFetchesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fetches_);
        onChanged();
      } else {
        fetchesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public Builder clearFetches() {
      if (fetchesBuilder_ == null) {
        fetches_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        fetchesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public Builder removeFetches(int index) {
      if (fetchesBuilder_ == null) {
        ensureFetchesIsMutable();
        fetches_.remove(index);
        onChanged();
      } else {
        fetchesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public ai.h2o.deepwater.backends.grpc.Tensor.Builder getFetchesBuilder(
        int index) {
      return getFetchesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public ai.h2o.deepwater.backends.grpc.TensorOrBuilder getFetchesOrBuilder(
        int index) {
      if (fetchesBuilder_ == null) {
        return fetches_.get(index);  } else {
        return fetchesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public java.util.List<? extends ai.h2o.deepwater.backends.grpc.TensorOrBuilder> 
         getFetchesOrBuilderList() {
      if (fetchesBuilder_ != null) {
        return fetchesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fetches_);
      }
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public ai.h2o.deepwater.backends.grpc.Tensor.Builder addFetchesBuilder() {
      return getFetchesFieldBuilder().addBuilder(
          ai.h2o.deepwater.backends.grpc.Tensor.getDefaultInstance());
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public ai.h2o.deepwater.backends.grpc.Tensor.Builder addFetchesBuilder(
        int index) {
      return getFetchesFieldBuilder().addBuilder(
          index, ai.h2o.deepwater.backends.grpc.Tensor.getDefaultInstance());
    }
    /**
     * <code>repeated .deepwater.Tensor fetches = 3;</code>
     */
    public java.util.List<ai.h2o.deepwater.backends.grpc.Tensor.Builder> 
         getFetchesBuilderList() {
      return getFetchesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ai.h2o.deepwater.backends.grpc.Tensor, ai.h2o.deepwater.backends.grpc.Tensor.Builder, ai.h2o.deepwater.backends.grpc.TensorOrBuilder> 
        getFetchesFieldBuilder() {
      if (fetchesBuilder_ == null) {
        fetchesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ai.h2o.deepwater.backends.grpc.Tensor, ai.h2o.deepwater.backends.grpc.Tensor.Builder, ai.h2o.deepwater.backends.grpc.TensorOrBuilder>(
                fetches_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        fetches_ = null;
      }
      return fetchesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:deepwater.TrainResponse)
  }

  // @@protoc_insertion_point(class_scope:deepwater.TrainResponse)
  private static final ai.h2o.deepwater.backends.grpc.TrainResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.h2o.deepwater.backends.grpc.TrainResponse();
  }

  public static ai.h2o.deepwater.backends.grpc.TrainResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrainResponse>
      PARSER = new com.google.protobuf.AbstractParser<TrainResponse>() {
    public TrainResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TrainResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TrainResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrainResponse> getParserForType() {
    return PARSER;
  }

  public ai.h2o.deepwater.backends.grpc.TrainResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

